apiVersion: batch/v1
kind: Job
metadata:
  name: rental-job-consumer-products
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: jornada-rental
          image: wesleywillians/rental_jornada:latest
          imagePullPolicy: Always
          command: ["php", "artisan","kafka:consume","products","product-group"]
          envFrom:
            - configMapRef:
                name: rental-app-conf
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rental-mysql-pass
                  key: password
          volumeMounts:
            - name: rental-app-conf
              subPath: .env
              mountPath: /var/www/.env

      volumes:
        - name: rental-app-conf
          configMap:
            name: rental-app-conf
            items:
              - key: env
                path: .env
