apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rental-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental-app

  template:
    metadata:
      labels:
        app: rental-app
    spec:
      containers:
      - name: jornada-rental
        image: wesleywillians/rental_jornada:latest
        imagePullPolicy: Always
#        command: ["/bin/sh", "-c", "ln -s /var/www /usr/share/nginx;  php-fpm;"]
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: rental-app-conf
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rental-mysql-pass
              key: password
        volumeMounts:
        - name: rental-app-conf
          subPath: .env
          mountPath: /var/www/.env  
      
      volumes:
      - name: rental-app-conf
        configMap:
          name: rental-app-conf
          items:
            - key: env
              path: .env
